### ISSUE TITLE
Feature Request: Can't xrpc update web_socket_channel ?

### ISSUE THREAD

**Issue by hidea** [myConsciousness/atproto.dart#1839]
## Proposal
Is it possible to update the web_socket_channel to 3.0.1 version?

I want to use package web: ^1.0.0 or over for other package(-> drift 2.21.0 or over).
Now, xrpc 0.6.0 depends on web_socket_channel: ^2.4.4,
and web_socket_channel >=2.4.4 <3.0.1 depends on web ^0.5.0

## Risks
web_socket_channel 3.0.0 seems to have some breaking changes.

**Comment by myConsciousness** [comment]
Hi @hidea ,

I changed it to use `web_socket_channel: ^3.0.0`, now you can try it :)
