### ISSUE TITLE
Improve Suggestion: make lib/main.dart at example directory.

### ISSUE THREAD

**Issue by tacsotai** [myConsciousness/atproto.dart#232]
Could you meke it as a normal plugin ?

# 1. What could be improved
I want just to run this with general way of flutter plugin project like below.
```
git clone https://github.com/myConsciousness/atproto.dart.git
cd atproto.dart/packages/bluesky/example
flutter run 
```
Of couse I know I have to chage some property for PDS server.

# 2. Why should this be improved
That's why it is easy to run.

# 3. Any risks?
I think there are no risks.

# 4. More information
https://docs.flutter.dev/development/packages-and-plugins/developing-packages
This is just the sample.
```
flutter create --template=plugin --platforms=android,ios -a java hello
cd hello
cd example
flutter run
```

**Comment by myConsciousness** [comment]
Hi @tacsotai ,

Why you need to do this? You can install `bluesky` package with dart command below:

```dart
dart pub add bluesky
```

- https://pub.dev/packages/bluesky

**Comment by tacsotai** [comment]
Because, I want to test your product before using your library.
It cost to use it with cording. It is good for me to run at first.

**Comment by myConsciousness** [comment]
@tacsotai ,

Hm, it's generally assumed that the example folder of a Dart package project contains only `example.dart`. 

It's true that if we create `main.dart`, we may be able to start it with `dart run`, but `example.dart` in this folder is not intended to be started as is. It is just a sample.

So, I feel the best way to test what Dart packages are like is to create your own empty Dart project and install the packages with `dart pub add` and `dart pub get` :)

**Comment by tacsotai** [comment]
Thank you for your consideration.
It is just a improve suggestion. 
I am also interested in atproto, so I thougt your code should be used by much people.
I will try it with your way.

If you want close this issue, please close it rr leave it for the future.

**Comment by myConsciousness** [comment]
@tacsotai ,

Please try this package that way!

If you have any improvements or additional specifications for the processing of the package, please don't hesitate to let me know. If you have any questions, please create a thread in this repository discussion :)
