### ISSUE TITLE
Feature Request: com.atproto.server.createAccount

### ISSUE THREAD

**Issue by tacsotai** [myConsciousness/atproto.dart#254]
Request for com.atproto.server.createAccount

# 1. Problem to solve

I need to create an account on my own pds server.
But I could not find the function.

# 2. Proposal

So, could you make a function to create acount ?
com.atproto.server.createAccount.

# 3. More information

**Comment by myConsciousness** [comment]
Hi @tacsotai !

Yes it's needed, I will implement soon!

**Comment by tacsotai** [comment]
Thank you. I am looking forward to be implemented.

**Comment by tacsotai** [comment]
Your service seems to be only for
https://bsky.social or https://foo.bar

I want to test it as
http://localhost:2583 or http://192.168.xxx.yyy

Could you support not only HTTPS but also HTTP ?
https://github.com/myConsciousness/atproto.dart/blob/main/packages/xrpc/lib/src/xrpc.dart#L150

**Comment by myConsciousness** [comment]
Hi @tacsotai ,

It's possible, I imaged an Enum like `Protocol` that would allow the user to select `HTTP` or `HTTPS`. Also, the default if this parameter is omitted would be `HTTPS`.

But since the Internet these days is based on `HTTPS` and you need to issue an SSL certificate and publish as `HTTPS` anyway, I don't know if we should provide an `HTTP` option. Is this option really necessary?

**Comment by myConsciousness** [comment]
@tacsotai ,

You can set HTTPS for localhost, like:

https://www.section.io/engineering-education/how-to-get-ssl-https-for-localhost/

**Comment by tacsotai** [comment]
Thank you for a information.
In my experience, it is good not using https while testing.
After test, go to staging env, https is good I was taught by senior.

Now I am investigating pds server.
https://zenn.dev/tac519/articles/727fca3783010c

And in the future, I gonna operate a small world with https://foo.bar/**hoge**
So, I want use the lib not only root domain and **sub folder.**

**Comment by myConsciousness** [comment]
@tacsotai 

I see, I'm going to add this option to atproto and bluesky, anyway I want to make these packages developer friendly:)

And do you need "createAccount" right now? I already implemented it and I can release, but I'm going to implement other endpoints to if it's not so urgent :)

**Comment by tacsotai** [comment]
Thank you for your consideration.
No, I want use it later. I am happy it will be relased in one month.
Actually, I am creating bluesky GUI client. I have also to create a little to access method.
https://github.com/tacsotai/flutter_bluesky

I want to use your library in my client because your libraly is shown at the [ecosystem](https://github.com/bluesky-social/atproto-ecosystem).

**Comment by myConsciousness** [comment]
@tacsotai 

It takes less than 2 weeks! I will release it as early as this Saturday or Sunday ;)

**Comment by myConsciousness** [comment]
Hi @tacsotai ,

I released new version of `atproto` and `bluesky` packages! I added `createAccount` and other endpoints, and added `protocol` parameter in `ATProto` and `Bluesky` object, you can set `Protocol.http` now :)

**Comment by tacsotai** [comment]
Thank you very much.
I will try it.

**Comment by tacsotai** [comment]
Now, I am trying below sample.
https://github.com/myConsciousness/atproto.dart/blob/main/packages/atproto/example/example.dart

```
    final session = await atp.createSession(
      service: 'SERVICE_NAME', //! The default is `bsky.social`
      identifier: 'YOUR_HANDLE_OR_EMAIL', //! Like `shinyakato.bsky.social`
      password: 'YOUR_PASSWORD',
    );
```

Can I set 'SERVICE_NAME' like '192.168.xxx.yyy:2583' ?
I got below error log on my M1 mac.
```
Unhandled exception:
HandshakeException: Handshake error in client (OS Error:
	WRONG_VERSION_NUMBER(tls_record.cc:242))
#0      _SecureFilterImpl._handshake (dart:io-patch/secure_socket_patch.dart:99:46)
#1      _SecureFilterImpl.handshake (dart:io-patch/secure_socket_patch.dart:142:25)
#2      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:915:54)
#3      _RawSecureSocket._closeHandler (dart:io/secure_socket.dart:908:15)
```

**Comment by myConsciousness** [comment]
Hi @tacsotai !

I use `http` package internally, so I guess it's possible to use local service name like that! Is this locally connectable server information?

**Comment by tacsotai** [comment]
Thank you for the reply.
I atatched protocol.
```
    final session = await atp.createSession(
      service: 'http://192.168.xxx.yyy:2583', 
;
```
Then I got another error.
```
Unhandled exception:
FormatException: Invalid radix-10 number (at character 1)
//192.168.xxx.yyy:2583
^

#0      int._handleFormatError (dart:core-patch/integers_patch.dart:126:5)
#1      int._parseRadix (dart:core-patch/integers_patch.dart:152:16)
#2      int._parse (dart:core-patch/integers_patch.dart:98:12)
#3      int.parse (dart:core-patch/integers_patch.dart:60:12)
#4      _Uri._makeHttpUri (dart:core/uri.dart:1791:49)
#5      new _Uri.https (dart:core/uri.dart:1693:12)
#6      new Uri.https (dart:core/uri.dart:272:20)
#7      procedure
xrpc.dart:291
#8      AnonymousClient.post
;
````

**Comment by myConsciousness** [comment]
@tacsotai ,

Please try with following:)

`service: '192.168.xxx.yyy:2583'`

**Comment by tacsotai** [comment]
Thanks. but in my env, [same](https://github.com/myConsciousness/atproto.dart/issues/254#issuecomment-1520967094) error occured.
The log tell me the problem on handshake. I will check it.
```
HandshakeException: Handshake error in client (OS Error:
	WRONG_VERSION_NUMBER(tls_record.cc:242))
```
