### ISSUE TITLE
Bug Report: @foo in message doesn't tag someone

### ISSUE THREAD

**Issue by lukepighetti** [myConsciousness/atproto.dart#291]
If you send a message with `@lukepighetti.bsky.social hello!` with `bluesky_cli` it will not actually link, it just comes in as plain text

**Comment by myConsciousness** [comment]
Hey @lukepighetti !

Interestingly, it does not interpret automatically like Twitter or Mastodon! We need to set `facet` parameter to make the mentions work, but this CLI does not support this param yet.

https://github.com/bluesky-social/atproto/blob/main/lexicons/app/bsky/feed/post.json

https://github.com/bluesky-social/atproto/blob/main/lexicons/app/bsky/richtext/facet.json

I will support it with other parameters soon, but if you want to try it out right away, please use the `Bluesky ` package! :)

https://pub.dev/packages/bluesky

**Comment by myConsciousness** [comment]
Or, I would automatically extract the mentions from the text and tie them to the profile. Perhaps this is easier to use :)

**Comment by myConsciousness** [comment]
Hi @lukepighetti ,

Fixed to automatically extract and resolve mention and link from text, and already released as `v0.1.2` :)
