### ISSUE TITLE
Improve Suggestion: Support `langs` in `PostRecord`

### ISSUE THREAD

**Issue by Uinelj** [myConsciousness/atproto.dart#640]
# 1. What could be improved

BlueSky posts now hold information about the language the posts are in. 
This info is in the JSON response but not in the Dart API.

# 2. Why should this be improved

It's info that can be easily added in the API, and would be useful to increase API coverage.

# 3. Any risks?

No breaking changes.

# 4. More information

I'd be willing to write the code, but I haven't been able to regenerate the `freeze`/`g` files after adding what's needed in `post_record.dart`.

As a sidenote, it would be useful to have some building information to help new contributors here :)

**Comment by myConsciousness** [comment]
Hi @Uinelj !

Apparently I didn't add this field to `PostRecord` object, good catch! Of course you can create a PR, thank you 👍
