### ISSUE TITLE
Posts generating "Rate Limited Exceeded Error"

### ISSUE THREAD

**Issue by rdelrossi** [myConsciousness/atproto.dart#820]
I run a real-time sports feed on Twitter that I've migrated over to Bluesky. I've been calling the Bluesky API using bsky. 

All has been well until recently. I see that bsky is returning a "RateLimitExceeded" error. I can, however, post to my account through the Bluesky web interface.

My question is, am I getting that error by misusing bsky (which is my guess, since the web interface works) or is my issue really with Bluesky itself?

Appreciate nay pointers, thank you!

**Comment by myConsciousness** [comment]
Hi @rdelrossi !

Just recently rate limits were added to almost all `atproto` and `bsky` endpoints. `.createSession` now has a particularly strict rate limit and requires proper session management.

Which package are you using for this project? Is it `bluesky_cli` or `bluesky`?

**Comment by rdelrossi** [comment]
Hi! Thank so much for your reply. I am using bluesky_cli. I just updated this morning to version 0.3.6, though I noticed (and can't quite figure out how to update) that cli_util is at version 0.3.5 with 0.4.0 available.

**Comment by myConsciousness** [comment]
Currently bluesky_cli does not support session management, but I will have to add this. Specifically, I will add a command to create a session and a command to refresh the session.

Then, I will add an option to pass an access token for each command that requires authentication!

**Comment by rdelrossi** [comment]
So, interestingly, after updating to 0.3.6 earlier today, I provided game coverage to Bluesky via bluesky_cli and it worked just fine. No rate limit exceeded errors despite many dozens of posts. I don’t know why it might have worked today, but I appreciate your responses here. Please let me know if I can help you with testing your upcoming session commands. I am very happy to help.

**Comment by myConsciousness** [comment]
@rdelrossi 

Apparently the session-related rate limits were an official bug. So it's now a lower priority, I will add commands for session management as noted above!

Apparently, posting images is a higher priority as you mentioned on #825 :)
