### ISSUE TITLE
Posting Images

### ISSUE THREAD

**Issue by rdelrossi** [myConsciousness/atproto.dart#825]
Is there a way to post images (JPG, PNG, etc) to Bluesky with bluesky_cli?

**Comment by myConsciousness** [comment]
Hi @rdelrossi ,

Now `bluesky_cli` does not support a way to post images, but I can add it and it's very easy :) I will let you know when it's released!

**Comment by myConsciousness** [comment]
@rdelrossi ,

Sorry for late response, but I added support for the `images` option to the `post` command of `bluesky_cli`. You can use as follows:

```bash
bsky post --text="test with images" --images=path/image1.png,path/image2.png
```

**Comment by rdelrossi** [comment]
This is outstanding, @myConsciousness. Thank you! A quick test worked perfectly for me. I'll test it a little more robustly and let you know if anything comes up. 

Thanks again!

**Comment by guidomz** [comment]
Does this mean the image need to be preloaded to bsky? Tried it using a url from my website, didn't work. How does this exactly work?

**Comment by guidomz** [comment]
> @rdelrossi ,
> 
> Sorry for late response, but I added support for the `images` option to the `post` command of `bluesky_cli`. You can use as follows:
> 
> ```shell
> bsky post --text="test with images" --images=path/image1.png,path/image2.png
> ```

Tried this using a url from my website, didn't work. How does this work? Does this mean the image need to be preloaded to bsky? If so, could you kindly show me how this is done?

**Comment by guidomz** [comment]
> > @rdelrossi ,
> > Sorry for late response, but I added support for the `images` option to the `post` command of `bluesky_cli`. You can use as follows:
> > ```shell
> > bsky post --text="test with images" --images=path/image1.png,path/image2.png
> > ```
> 
> Tried this using a url from my website, didn't work. How does this work? Does this mean the image need to be preloaded to bsky? If so, could you kindly show me how this is done?

I got this figured out. The `--images` argument can take only local files relative to the execution of `bsky` and will not fetch it from a remote. Thanks.
